### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by xaerincl** [notAI-tech/NudeNet#11]
Is there any way i can get the dataset for the object recognition ?

i would like to make make a mobilenet ssd version of your model.

**Comment by bedapudi6788** [comment]
@xaerincl I am sorry, I cannot share the dataset. But, I can train mobilenet ssd version and open-source the weights. Let me know if you need that.

**Comment by xaerincl** [comment]
Yo that would be great!

**Comment by bedapudi6788** [comment]
https://github.com/notAI-tech/NudeNet/issues/53#issuecomment-717942337
