### ISSUE TITLE
Is it possible to get ONNX-format model?

### ISSUE THREAD

**Issue by victor-mikhalev** [notAI-tech/NudeNet#27]
Is it possible to get ONNX-format model?

**Comment by christopherfowers** [comment]
Bump. An onnx format model would be insanely useful to the community. Is this on the roadmap yet? If so where does this fall in priorities?

**Comment by bedapudi6788** [comment]
At the moment, this is not on my priority list. If you are able to convert the pre-trained models to onnx, please submit a pr/ example code on how to run inference with onnx format model and I will add it to the repo.

**Comment by selrahc** [comment]
I used command below to generate an ONNX format model.
```
!pip install tf2onnx
!python -m tf2onnx.convert \
        --inputs input_1:0 \
        --opset 12 \
        --saved-model ./default/detector_v2_default_checkpoint_tf \
        --output ./model.onnx
```

To run inference, I used code below.
```
!pip install onnxruntime

from detector_utils import preprocess_image
import numpy as np
import onnxruntime as rt

image, scale = preprocess_image('./rga6845.jpg')
sample = np.expand_dims(image, axis=0)

onnx_path = './model.onnx'
sess = rt.InferenceSession(onnx_path)
x_name = sess.get_inputs()[0].name
y1_name = sess.get_outputs()[0].name
y2_name = sess.get_outputs()[1].name
y3_name = sess.get_outputs()[2].name
outPred = sess.run([y1_name, y2_name, y3_name], {x_name: sample})

print(outPred)
```

But its result is not very well. The highest score is just 0.28650916 -> There is no problem for now (score is 0.7914443)! Please see the new comments (cf. https://github.com/notAI-tech/NudeNet/issues/62#issuecomment-756725709).

**Comment by bedapudi6788** [comment]
Closing this, since this is resolved in the link above.
