### ISSUE TITLE
i am just trying to execute a sample code but getting this error , everytime i run it., i did this using ubuntu system, run the same code in macbook pro 2016 ,the code is fine and worked also, but in ubuntu getting error

### ISSUE THREAD

**Issue by hemantraju123** [notAI-tech/NudeNet#36]
this is my code

from nudenet import NudeClassifier
def image_prediction():
    classifier = NudeClassifier()
    classifier.classify('/home/vhr/Desktop/abc/abc.jpg')
    
if __name__ == '__main__':
    image_prediction()

error is

ile "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 9437184, sblock->base_addr = 0, stored_eof = 223178568)

**Comment by bedapudi6788** [comment]
> OSError: Unable to open file (truncated file: eof = 9437184, sblock->base_addr = 0, stored_eof = 223178568)


The checkpoint was not downloaded properly. 

```bash
rm -rf ~/.NudeNet
```

```python
from nudenet import NudeClassifier
classifier = NudeClassifier()
```

should fix this issue.
